version: "3"
services:
  object-detector:
    build:
      context: .
      dockerfile: dockerfile
    container_name: yolov5-detector
    ports:
      - "8000:8000"
    image: yolov5
    volumes:
      - ./:/object-detection-yolov5
